package net.dean.jraw.models;

import com.google.auto.value.AutoValue;
import com.squareup.moshi.Json;
import com.squareup.moshi.JsonAdapter;
import com.squareup.moshi.Moshi;
import net.dean.jraw.databind.RedditModel;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.io.Serializable;

@AutoValue
@RedditModel
public abstract class Trophy implements Identifiable, Serializable {
    /** A succinct description of how/when/why the user got this award */
    @Nullable
    public abstract String getDescription();

    /** Trophy name (e.g. "Five-Year Club") */
    @NotNull
    @Override
    @Json(name = "name") public abstract String getFullName();

    /**
     * An optional URL that highlights where/how the user gained the trophy. If this URL is relative, it is relative to
     * `reddit.com`
     */
    @Nullable
    public abstract String getUrl();

    /** A unique ID generated by reddit, if any */
    @Nullable
    @Override
    public abstract String getId();

    /** The 40x40 icon for this Trophy */
    @Json(name = "icon_40") public abstract String getIcon40();

    /** The 70x70 icon for this Trophy */
    @Json(name = "icon_70") public abstract String getIcon70();

    public static JsonAdapter<Trophy> jsonAdapter(Moshi moshi) {
        return new AutoValue_Trophy.MoshiJsonAdapter(moshi);
    }
}
