package net.dean.jraw.models

import com.fasterxml.jackson.annotation.JsonIgnore
import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.annotation.JsonDeserialize
import net.dean.jraw.databind.UnixTimeDeserializer
import java.util.*

@JsonIgnoreProperties(ignoreUnknown = true)
data class Account(
    /** The amount of Karma this user has acquired through comments */
    val commentKarma: Int,

    @JsonProperty("created_utc")
    @JsonDeserialize(using = UnixTimeDeserializer::class)
    override val created: Date,

    /** A unique identifier generated by reddit */
    val id: String,

    /** If the currently logged in user is friends with this account */
    val isFriend: Boolean,

    /** If this user is a moderator */
    @JsonProperty("is_mod") val isModerator: Boolean,

    /** If this */
    @JsonProperty("is_gold") val hasGold: Boolean,
    val hasSubscribed: Boolean,
    val hasVerifiedEmail: Boolean,
    val linkKarma: Int,

    /** The name chosen for this account by a real person */
    val name: String,
    val verified: Boolean
) : Thing(ThingType.ACCOUNT), Created

